const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Berlin',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const link=(url,label)=>'<a href="'+esc(url)+'" >'+esc(label)+'</a>';
let D,mailType='all',mailLimit=5,jobLimit=6;
function emailType(e){return /proposal.*viewed|interview|sent you a message|new message|reply|offer|invitation/i.test(e.subject)?'response':e.labels.includes('CATEGORY_PROMOTIONS')?'promotion':'account'}
function renderProposals(){const rows=D.proposals.filter(p=>(p.marketplaceJobPosting.content.title+' '+(p.country||'')).toLowerCase().includes($('#search').value.toLowerCase())&&($('#status').value==='all'||p.status.status_label===$('#status').value)&&($('#period').value!=='today'||p.auditDetails.createdDateTime.displayValue.startsWith('2026-10-02'))&&($('#period').value!=='week'||p.auditDetails.createdDateTime.displayValue>='2026-09-26'));
$('#proposals').innerHTML=rows.map(p=>'<tr><td>'+link(p.marketplaceJobPosting.url,p.marketplaceJobPosting.content.title)+'<small>'+esc(p.country||'SAMPLE DATA · Location unavailable')+' · '+(p.boosted?'Boosted':'Standard')+'</small></td><td><span class="status">'+esc(p.status.status_label)+'</span></td><td>'+date(p.auditDetails.createdDateTime.displayValue)+'</td><td>'+esc(p.terms.chargeRate.displayValue)+'<small>Stored Connects bid: '+esc(p.terms.connectsBid??'Unavailable')+'</small></td></tr>').join('')||'<tr><td colspan="4">No proposals match these filters.</td></tr>';$('#proposaltotal').textContent=rows.length+' of '+D.proposals.length+' submitted proposals. Stored Connects bids are not transaction charges.'}
function renderMail(){const items=D.emails.filter(e=>mailType==='all'||emailType(e)===mailType);$('#emails').innerHTML=items.slice(0,mailLimit).map(e=>'<div class="listitem">'+link(e.display_url,e.subject)+'<p>'+date(e.email_ts)+' · '+esc(emailType(e))+(e.labels.includes('UNREAD')?' · Unread':'')+'</p></div>').join('')||'<p class="empty">No matching email notifications in the returned results.</p>';$('#moremail').classList.toggle('hidden',items.length<=mailLimit)}
function renderJobs(){const rows=D.dashboard.matching_jobs.jobs.filter(j=>j.title.toLowerCase().includes($('#jobsearch').value.toLowerCase())&&($('#country').value==='all'||j.client.country===$('#country').value)&&($('#jobtype').value==='all'||j.job_type===$('#jobtype').value));$('#joblist').innerHTML=rows.slice(0,jobLimit).map(j=>'<article class="job"><h3>'+link(j.url,j.title)+'</h3><div class="row"><span>'+esc(j.budget||'Rate not stated')+'</span><small>'+esc(j.job_type)+'</small></div><small>'+esc(j.client.country)+' · '+esc(j.client.verification_status==='VERIFIED'?'Payment verified':'Payment not verified')+'</small><p>'+esc(j.proposals_tier)+' proposals · '+date(j.published_date)+'</p><p>'+esc(j.skills.slice(0,4).join(' · '))+'</p>'+link(j.url,'View job on Upwork')+'</article>').join('')||'<p class="empty">No matching jobs with these filters.</p>';$('#jobcount').textContent=rows.length+' jobs in this preview · Full feed may contain more';$('#morejobs').classList.toggle('hidden',rows.length<=jobLimit)}
function populate(){const d=D.dashboard;$('#checked').textContent='Sample dataset dated '+date(D.checkedAt)+' · Europe/Berlin';$('#sourcedate').textContent=$('#checked').textContent;
const k=[['Submitted proposals',D.proposals.length,'Submitted status only'],['Invitations',d.invitations.count,'Pending invitations'],['Offers',d.offers.count,'Received offers'],['Message rooms',d.messages.count,'Unread in preview: '+d.messages.unread_in_preview],['Active contracts',d.active_contracts.total_count,'Demo account'],['Connects balance',D.connects.balance.connectsBalance,'Sample balance']];
$('#kpis').innerHTML=k.map(([label,value,note])=>'<div class="kpi"><div class="label">'+label+'</div><div class="value">'+value+'</div><small>'+note+'</small><span class="tag">SAMPLE DATA</span></div>').join('');
$('#stages').innerHTML=[['Submitted',D.proposals.length],['View notifications',D.emails.filter(e=>/proposal.*viewed/i.test(e.subject)).length],['Offers',d.offers.count],['Active contracts',d.active_contracts.total_count]].map(([name,n])=>'<div class="stage"><strong>'+n+'</strong><small>'+name+'</small></div>').join('');
const responses=D.emails.filter(e=>emailType(e)==='response');$('#alerts').innerHTML=responses.map(e=>'<div class="listitem"><span class="status">Proposal view notification</span><p>'+link(e.display_url,e.subject)+'</p><small>'+date(e.email_ts)+' · Not linked to a proposal from the available email metadata</small></div>').join('')||'<p class="empty">No response notifications found.</p>';
$('#alerts').innerHTML+='<p class="empty">All notifications and account totals are fictional examples.</p>';
$('#accountactivity').innerHTML=['Invitations: '+d.invitations.count,'Offers: '+d.offers.count,'Message rooms in snapshot: '+d.messages.count,'Active contracts: '+d.active_contracts.total_count].map(t=>'<div class="listitem">'+t+'</div>').join('');
const b=D.connects.balance;$('#balance').textContent=b.connectsBalance;$('#breakdown').innerHTML=[['Free',b.connectsBalanceFree],['Paid',b.connectsBalancePaid],['Rollover',b.rolloverBalance]].map(([k,v])=>'<span>'+k+'<b>'+v+'</b></span>').join('');
const tx=D.connects.usage_history.transactions,days={};for(const t of tx){const v=Number(t.amount.rawValue);if(v<0){const day=t.createdDateTime.slice(0,10);days[day]=(days[day]||0)-v}}const max=Math.max(...Object.values(days),1);$('#chart').innerHTML=Object.entries(days).sort().map(([day,v])=>'<div class="bar"><b>'+v+'</b><i style="height:'+Math.max(2,v/max*78)+'px"></i>'+date(day+'T12:00:00Z').split(',')[0].replace('14:00','')+'</div>').join('');
$('#usage').innerHTML=tx.slice(0,5).map(t=>'<div class="listitem"><div class="row"><span>'+esc(t.reason)+'</span><b>'+esc(t.amount.rawValue)+'</b></div><small>'+esc(t.jobPost?.jobTitle||'Account credit')+' · '+date(t.createdDateTime)+'</small></div>').join('');
const feed=[...D.proposals.map(p=>({time:p.auditDetails.createdDateTime.displayValue,title:'Proposal submitted',body:p.marketplaceJobPosting.content.title,url:p.marketplaceJobPosting.url})),...tx.map(t=>({time:t.createdDateTime,title:t.reason,body:t.amount.rawValue+' Connects · '+(t.jobPost?.jobTitle||'Account'),url:'#demo-record'})),...responses.map(e=>({time:e.email_ts,title:'Proposal viewed notification',body:e.subject,url:e.display_url}))].sort((a,b)=>b.time.localeCompare(a.time));
$('#feed').innerHTML=feed.slice(0,8).map(e=>'<div class="listitem"><h3>'+link(e.url,e.title)+'</h3><p>'+esc(e.body)+'</p><small>'+date(e.time)+'</small></div>').join('');
for(const country of [...new Set(d.matching_jobs.jobs.map(j=>j.client.country))].sort()){$('#country').add(new Option(country,country))}
renderProposals();renderMail();renderJobs();}
async function map(){const world=await fetch('world.json').then(r=>r.json());const svg=$('#world'),ns='http://www.w3.org/2000/svg';const point=([lon,lat])=>[(lon+180)*2.5,(90-lat)*2.5];for(const f of world.features){const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;for(const polygon of polygons){const path=document.createElementNS(ns,'path');path.setAttribute('d',polygon.map(ring=>ring.map((p,i)=>(i?'L':'M')+point(p).join(',')).join(' ')+'Z').join(' '));svg.append(path)}}const centers={'Pakistan':[69.3,30.4],'United States':[-98.5,39.8],'Turkey':[35.2,39]};for(const [name,coords] of Object.entries(centers)){const ps=D.proposals.filter(p=>p.country===name);if(!ps.length)continue;const circle=document.createElementNS(ns,'circle');const [x,y]=point(coords);circle.setAttribute('cx',x);circle.setAttribute('cy',y);circle.setAttribute('r',5+ps.length);circle.setAttribute('tabindex','0');circle.setAttribute('role','button');circle.setAttribute('aria-label',name+': '+ps.length+' proposals');const title=document.createElementNS(ns,'title');title.textContent=name+' · '+ps.length+' proposals';circle.append(title);const select=()=>{$('#mapselection').textContent=name+' · '+ps.length+' submitted '+(ps.length===1?'proposal':'proposals')+': '+ps.map(p=>p.marketplaceJobPosting.content.title).join('; ')};circle.addEventListener('click',select);circle.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}});svg.append(circle)}}
['search','status','period'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderProposals));['jobsearch','country','jobtype'].forEach(id=>$('#'+id).addEventListener(id==='jobsearch'?'input':'change',()=>{jobLimit=6;renderJobs()}));
$('#mailtabs').addEventListener('click',e=>{if(!e.target.dataset.type)return;mailType=e.target.dataset.type;mailLimit=5;document.querySelectorAll('#mailtabs button').forEach(b=>b.classList.toggle('selected',b===e.target));renderMail()});$('#moremail').onclick=()=>{mailLimit+=10;renderMail()};$('#morejobs').onclick=()=>{jobLimit+=6;renderJobs()};$('#sources').onclick=()=>$('#dialog').showModal();$('#close').onclick=()=>$('#dialog').close();$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(D,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='upwork-tracker-demo.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};document.querySelectorAll('.nav a').forEach(a=>a.onclick=()=>{document.querySelectorAll('.nav a').forEach(n=>n.classList.toggle('active',n===a))});
fetch('data.json').then(r=>{if(!r.ok)throw Error('Snapshot unavailable');return r.json()}).then(d=>{D=d;populate();map().catch(()=>{$('#mapselection').textContent='SAMPLE DATA · Map boundaries unavailable. Sample client countries remain in the proposal table.'})}).catch(()=>{$('#checked').textContent='SAMPLE DATA · Snapshot could not be loaded. Please reload.'});

document.addEventListener('click',e=>{if(e.target.closest('a[href="#demo-record"]')){e.preventDefault();document.querySelector('#dialog').showModal();}});
